# Magic Square

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from data import *
from checker import is_magic, magic_sum

In [3]:
square3_ok

array([[2, 7, 6],
       [9, 5, 1],
       [4, 3, 8]])

In [4]:
print(square3_ok)

[[2 7 6]
 [9 5 1]
 [4 3 8]]


In [5]:
square3_ok[0].sum()

15

In [8]:
is_magic(square3_ok)

False

In [7]:
magic_sum(4)

34

In [9]:
square3_ok.diagonal()

array([2, 5, 8])

In [12]:
square3_ok[::-1]

array([[4, 3, 8],
       [9, 5, 1],
       [2, 7, 6]])

In [13]:
square3_ok[::-1].diagonal()

array([4, 5, 6])

In [15]:
np.trace(square3_ok), \
np.trace(square3_ok[::-1]),

(15, 15)

In [10]:
square3_ok.T

array([[2, 9, 4],
       [7, 5, 3],
       [6, 1, 8]])